package tn.isg.economics.ai;

import tn.isg.economics.model.PricePrediction;
import tn.isg.economics.service.ReportGenerator;
import tn.isg.economics.util.ConfigLoader;

import java.util.List;
import java.util.stream.Collectors;

public class LLMReportService implements ReportGenerator {
    
    public LLMReportService() {
        // Constructor - could initialize LLM connection here
    }
    
    @Override
    public String generateMarketReport(List<PricePrediction> predictions) {
        StringBuilder report = new StringBuilder();
        report.append("=== MARKET INTELLIGENCE REPORT ===\n\n");
        report.append("Generated on: ").append(java.time.LocalDate.now()).append("\n");
        report.append("Total Predictions: ").append(predictions.size()).append("\n\n");
        
        // Group by product
        var byProduct = predictions.stream()
            .collect(Collectors.groupingBy(PricePrediction::productType));
        
        for (var entry : byProduct.entrySet()) {
            report.append("## Product: ").append(entry.getKey().getFrenchName()).append("\n");
            
            double avgPrice = entry.getValue().stream()
                .mapToDouble(PricePrediction::predictedPrice)
                .average().orElse(0.0);
            
            double avgConfidence = entry.getValue().stream()
                .mapToDouble(PricePrediction::confidence)
                .average().orElse(0.0);
            
            report.append(String.format("Average Predicted Price: $%.2f/ton\n", avgPrice));
            report.append(String.format("Average Confidence: %.1f%%\n", avgConfidence * 100));
            
            // Simple trend analysis
            if (avgConfidence > 0.8) {
                report.append("Trend: Strong prediction reliability\n");
            } else if (avgConfidence > 0.6) {
                report.append("Trend: Moderate prediction reliability\n");
            } else {
                report.append("Trend: Low prediction reliability - caution advised\n");
            }
            report.append("\n");
        }
        
        // Market recommendations
        report.append("=== RECOMMENDATIONS ===\n");
        report.append("1. Monitor olive oil prices closely - highest volatility expected\n");
        report.append("2. Consider forward contracts for dates during peak season\n");
        report.append("3. Citrus fruits show stable trends - good for consistent exports\n");
        report.append("4. Weather patterns suggest potential impact on wheat yields\n\n");
        
        report.append("Report generated by Tunisian Agricultural Export AI System\n");
        
        return report.toString();
    }
    
    @Override
    public String generateSummaryReport(List<PricePrediction> predictions) {
        double avgConfidence = predictions.stream()
            .mapToDouble(PricePrediction::confidence)
            .average().orElse(0.0);
        
        long highConfidence = predictions.stream()
            .filter(p -> p.confidence() > 0.7)
            .count();
        
        return String.format(
            "Executive Summary: %d price predictions analyzed with %.1f%% average confidence. " +
            "%d predictions have high confidence (>70%%). Market shows mixed trends with " +
            "opportunities in premium products.",
            predictions.size(), avgConfidence * 100, highConfidence
        );
    }
}
